version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dispia-backend
    restart: always
    # MUDANÇA AQUI: Adicionado '--transpile-only' para evitar crash de memória e erros de tipo em tempo real
    command: sh -c "npx prisma generate && npx ts-node --transpile-only src/index.ts"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dispia-net
    depends_on:
      - db

  frontend:
    build: ./dispia-frontend
    container_name: dispia-frontend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./dispia-frontend:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - dispia-net
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: dispia-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dispia-net

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - dispia-net

networks:
  dispia-net:
    driver: bridge

volumes:
  postgres_data: